[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "test/data" }]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/6c80b4478d644647bcc2671e06966b23"
